services:
    mysqlDB:
        image: mysql:9
        restart: always
        container_name: mysql_service
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_DATABASE=${DB_DATABASE}
        volumes:
            - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'mysqladmin ping -h 127.0.0.1 -u root -p${DB_ROOT_PASSWORD} --silent',
                ]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 10s
    nginx_frontend:
        image: nginx
        restart: always
        container_name: nginx_service
        volumes:
            - ./build_frontend:/usr/share/nginx/html # build Vite
            - ./nginx_conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf # proxy for nginx
        ports:
            - '80:80'
        depends_on:
            - php
    php:
        build: .
        restart: always
        container_name: php_service
        volumes:
            - ./laravel:/var/laravel # PHP Laravel build
        working_dir: /var/laravel
        tty: true
volumes:
    mysqldb_data:
